[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
unichain_sepolia = "https://sepolia.unichain.org"
unichain_mainnet = "https://mainnet.unichain.org"
base_sepolia = "https://sepolia.base.org"
base_mainnet = "https://mainnet.base.org"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
